displayName=Chat Highlight Player
author=kat and Aiirik
description=Highlight players by clicking their names in chat.
tags=Chat,text,highlight,player,trade
plugins=com.chathighlightplayer.ChatHighlightPlayerPlugin
version= 2.0.1
build=standard

