displayName=Chat Highlight Player
author=kat and Aiirik
description=Highlight Player when click on name in chat!
tags=Chat,text,highlight,player,trade
plugins=com.chathighlightplayer.ChatHighlightPlayerPlugin
build=standard
